version: '3.9'

services:
  nginx:
    container_name: nginx-container
    build: requirements/nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp_statics:/var/www/html/wordpress
    networks:
      - inception
  
  wordpress:
    container_name: wp-container
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp_statics:/var/www/html/wordpress
    env_file:
      - .env

  mariadb:
    container_name: mariadb-container
    build: requirements/mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  wp_statics:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tdeville/data/wordpress'

  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tdeville/data/database'
